Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

TrivialAccessors:
  Enabled: false

RedundantReturn:
  Enabled: false

ModuleLength:
  Enabled: false

Encoding:
  EnforcedStyle: when_needed

LineLength:
  Max: 180

MethodLength:
  Max: 11

Style/RegexpLiteral:
  Enabled: false
